### ISSUE TITLE
Make and push a README.md

### ISSUE THREAD

**Issue by unintendedbear** [MusesProject/Muses-Developer-Guide#1]
Explaining the document and including a link to the last release.

No one is assigned, but of course, everyone can do it.

**Comment by unintendedbear** [comment]
Thank you @JJ !

**Comment by aesparcia** [comment]
Esta cuenta no est� operativa, si desea contactar conmigo h�galo a esta
direcci�n:
aesparcia@ieee.org

Si necesita contactar con alguien de S2 Grupo, h�galo a la direcci�n
mjuan@s2grupo.es

---

This account does not work, if you want to contact me, please use this
e-mail:
aesparcia@ieee.org

If you need to contact someone from S2 Group, do it to the e-mail
miguel.juan@s2grupo.es

Nota: Esta es una respuesta autom�tica a su mensaje
"[Muses-Developer-Guide] Make and push a README.md (#1)" enviado el
12/03/2015 10:53:48.

Esta es la �nica notificaci�n que recibir� mientras esta persona est�
ausente.

**Comment by aesparcia** [comment]
Esta cuenta no est� operativa, si desea contactar conmigo h�galo a esta
direcci�n:
aesparcia@ieee.org

Si necesita contactar con alguien de S2 Grupo, h�galo a la direcci�n
mjuan@s2grupo.es

---

This account does not work, if you want to contact me, please use this
e-mail:
aesparcia@ieee.org

If you need to contact someone from S2 Group, do it to the e-mail
miguel.juan@s2grupo.es

Nota: Esta es una respuesta autom�tica a su mensaje  "Re:
[Muses-Developer-Guide] Make and push a README.md (#1)" enviado el
12/03/2015 11:21:26.

Esta es la �nica notificaci�n que recibir� mientras esta persona est�
ausente.

**Comment by aesparcia** [comment]
Esta cuenta no est� operativa, si desea contactar conmigo h�galo a esta
direcci�n:
aesparcia@ieee.org

Si necesita contactar con alguien de S2 Grupo, h�galo a la direcci�n
mjuan@s2grupo.es

---

This account does not work, if you want to contact me, please use this
e-mail:
aesparcia@ieee.org

If you need to contact someone from S2 Group, do it to the e-mail
miguel.juan@s2grupo.es

Nota: Esta es una respuesta autom�tica a su mensaje  "Re:
[Muses-Developer-Guide] Make and push a README.md (#1)" enviado el
12/03/2015 11:21:54.

Esta es la �nica notificaci�n que recibir� mientras esta persona est�
ausente.
