### ISSUE TITLE
On the Introduction, add description of MusesSituationPredictionStudy repository

### ISSUE THREAD

**Issue by unintendedbear** [MusesProject/Muses-Developer-Guide#3]
And update the repository info with that line.

**Comment by aesparcia** [comment]
Esta cuenta no est� operativa, si desea contactar conmigo h�galo a esta
direcci�n:
aesparcia@ieee.org

Si necesita contactar con alguien de S2 Grupo, h�galo a la direcci�n
mjuan@s2grupo.es

---

This account does not work, if you want to contact me, please use this
e-mail:
aesparcia@ieee.org

If you need to contact someone from S2 Group, do it to the e-mail
miguel.juan@s2grupo.es

Nota: Esta es una respuesta autom�tica a su mensaje
"[Muses-Developer-Guide] On the Introduction, add description of
MusesSituationPredictionStudy repository (#3)" enviado el 12/03/2015
12:10:51.

Esta es la �nica notificaci�n que recibir� mientras esta persona est�
ausente.

**Comment by aesparcia** [comment]
Esta cuenta no est� operativa, si desea contactar conmigo h�galo a esta
direcci�n:
aesparcia@ieee.org

Si necesita contactar con alguien de S2 Grupo, h�galo a la direcci�n
mjuan@s2grupo.es

---

This account does not work, if you want to contact me, please use this
e-mail:
aesparcia@ieee.org

If you need to contact someone from S2 Group, do it to the e-mail
miguel.juan@s2grupo.es

Nota: Esta es una respuesta autom�tica a su mensaje  "Re:
[Muses-Developer-Guide] On the Introduction, add description of
MusesSituationPredictionStudy repository (#3)" enviado el 13/03/2015
12:07:04.

Esta es la �nica notificaci�n que recibir� mientras esta persona est�
ausente.
