### ISSUE TITLE
On the Introduction, add description of MusesCommon repository

### ISSUE THREAD

**Issue by unintendedbear** [MusesProject/Muses-Developer-Guide#4]
And update repository info with that line.

**Comment by aesparcia** [comment]
Esta cuenta no est� operativa, si desea contactar conmigo h�galo a esta
direcci�n:
aesparcia@ieee.org

Si necesita contactar con alguien de S2 Grupo, h�galo a la direcci�n
mjuan@s2grupo.es

---

This account does not work, if you want to contact me, please use this
e-mail:
aesparcia@ieee.org

If you need to contact someone from S2 Group, do it to the e-mail
miguel.juan@s2grupo.es

Nota: Esta es una respuesta autom�tica a su mensaje
"[Muses-Developer-Guide] On the Introduction, add description of
MusesCommon repository (#4)" enviado el 12/03/2015 12:14:44.

Esta es la �nica notificaci�n que recibir� mientras esta persona est�
ausente.

**Comment by aesparcia** [comment]
Esta cuenta no est� operativa, si desea contactar conmigo h�galo a esta
direcci�n:
aesparcia@ieee.org

Si necesita contactar con alguien de S2 Grupo, h�galo a la direcci�n
mjuan@s2grupo.es

---

This account does not work, if you want to contact me, please use this
e-mail:
aesparcia@ieee.org

If you need to contact someone from S2 Group, do it to the e-mail
miguel.juan@s2grupo.es

Nota: Esta es una respuesta autom�tica a su mensaje  "Re:
[Muses-Developer-Guide] On the Introduction, add description of MusesCommon
repository (#4)" enviado el 12/03/2015 17:51:29.

Esta es la �nica notificaci�n que recibir� mientras esta persona est�
ausente.
