### ISSUE TITLE
Add \url to URLs

### ISSUE THREAD

**Issue by JJ** [MusesProject/Muses-Developer-Guide#8]
So that they can be clickable...

**Comment by unintendedbear** [comment]
I've checked the .tex and every URL is between \url{}, but it's true that they're not clickable on the PDF... I don't know why is this happening.

**Comment by aesparcia** [comment]
Esta cuenta no est� operativa, si desea contactar conmigo h�galo a esta
direcci�n:
aesparcia@ieee.org

Si necesita contactar con alguien de S2 Grupo, h�galo a la direcci�n
mjuan@s2grupo.es

---

This account does not work, if you want to contact me, please use this
e-mail:
aesparcia@ieee.org

If you need to contact someone from S2 Group, do it to the e-mail
miguel.juan@s2grupo.es

Nota: Esta es una respuesta autom�tica a su mensaje  "Re:
[Muses-Developer-Guide] Add \url to URLs (#8)" enviado el 22/03/2015
21:19:01.

Esta es la �nica notificaci�n que recibir� mientras esta persona est�
ausente.

**Comment by aesparcia** [comment]
Esta cuenta no est� operativa, si desea contactar conmigo h�galo a esta
direcci�n:
aesparcia@ieee.org

Si necesita contactar con alguien de S2 Grupo, h�galo a la direcci�n
mjuan@s2grupo.es

---

This account does not work, if you want to contact me, please use this
e-mail:
aesparcia@ieee.org

If you need to contact someone from S2 Group, do it to the e-mail
miguel.juan@s2grupo.es

Nota: Esta es una respuesta autom�tica a su mensaje
"[Muses-Developer-Guide] Add \url to URLs (#8)" enviado el 22/03/2015
20:33:16.

Esta es la �nica notificaci�n que recibir� mientras esta persona est�
ausente.
